# _config.yml
title: Karthik Prabhu Palimar
email: karthikprabhu22@gmail.com
description: >-
  Physics Ph.D. Candidate at UC Davis specializing in Computational Cosmology, 
  Machine Learning, and High-Dimensional Data Analysis.
url: "https://karthikprabhu22.github.io"
baseurl: "" 

author:
  name: "Karthik Prabhu Palimar"
  avatar: "pic.jpg"
  bio: "Your bio here"
  location: "Davis, USA"

#Social links
social:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/karthikprabhu22"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://linkedin.com/in/kprabhu22"
  - label: "arXiv"
    icon: "ai ai-arxiv"
    url: "https://arxiv.org/search/"

header_pages:
  - about.md
  - research.md
  - publications.md
  - projects.md
  - teaching.md
  - cv.md
  
  
# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache  
  - jekyll-seo-tag


